### ISSUE TITLE
Speed of update

### ISSUE THREAD

**Issue by Russ76** [bstarbuck3/mdek_driver#1]
Do you find speed of location measure and data transfer acceptable? Using the MDEK with Android tablet, 4 anchors and 1 tag, walking around, it seems slow, too slow to use with a robot.

**Comment by bstarbuck3** [comment]
Hello Russ76, my code does not use the Android tablet, therefore I have never used their interface and don't know what your settings are.  For robot integration, ROS will give you much more customization.  Second, ultra-wideband in general can update within nanoseconds due to the way it sends short burst of data, so yes, it works for robot localization, and I have successfully used the MDEK kit for that.  I recommend that you check the DWM1001 API Guide where you will see that you can send a command to the modules and set the stationary and moving update frequencies to be faster as needed.  Check 5.34 aurs command and for specifics, 4.3.3 dwm_upd_rate_set. Good luck, hope this helps!

**Comment by Russ76** [comment]
Thanks for speedy answer! Their Android software makes setup very easy, but the speed penalty is the price, I guess. I will roll up my sleeves and check that code. Mine will have to cover 40 meters. May have to turn up radio power. I like their MDEK interface cards, it looks like they should be a tremendous help.
